---
title: "EDA"
output: html_document
---
```{r}
library(tidyverse)
library(tidytuesdayR)
```

```{r}
tuesdata <- tidytuesdayR::tt_load(2025, week = 26)

weekly_gas_prices <- tuesdata$weekly_gas_prices
```

# Columns exploration

```{r}
weekly_gas_prices |>
  count(year(date)) |>
  print(n = 50)

weekly_gas_prices |>
  count(fuel, year(date)) |>
  print(n = 80)

weekly_gas_prices |>
  distinct(grade)

weekly_gas_prices |>
  distinct(formulation)

weekly_gas_prices |>
  filter(!is.na(formulation), fuel == "diesel")
```

# Price per year

```{r}
weekly_gas_prices |>
  group_by(year = year(date), fuel) |>
  summarise(
    avg_price = mean(price),
    .groups = "drop"
  ) |>
  ggplot(aes(x = year, y = avg_price)) +
  geom_line(aes(group = fuel, color = fuel), linewidth = 1) +
  scale_y_continuous(breaks = seq(0, 5, 0.5))
```

# How did gas prices behave during major events like the 2008 recession or COVID-19 pandemic?

```{r}
weekly_gas_prices |>
  group_by(year = year(date), fuel) |>
  summarise(
    avg_price = mean(price),
    .groups = "drop"
  ) |>
  ggplot(aes(x = year, y = avg_price)) +
  geom_line(aes(group = fuel, color = fuel), linewidth = 1) +
  scale_x_continuous(limits = c(2007, 2010))
  scale_y_continuous(breaks = seq(0, 5, 0.5))
  
weekly_gas_prices |>
  group_by(year = year(date), fuel) |>
  summarise(
    avg_price = mean(price),
    .groups = "drop"
  ) |>
  ggplot(aes(x = year, y = avg_price)) +
  geom_line(aes(group = fuel, color = fuel), linewidth = 1) +
  scale_x_continuous(limits = c(2018, 2025))
  scale_y_continuous(breaks = seq(0, 5, 0.5))
```

# Are diesel prices more or less volatile than gasoline prices?

```{r}
weekly_gas_prices |>
  mutate(
    year = factor(year(date))
  ) |>
  filter(
    year %in% seq(2006, 2010, 1)
  ) |>
  ggplot(aes(x = year, y = price, fill = fuel)) +
  geom_boxplot() +
  scale_fill_discrete(labels = c("diesel" = "Diesel", "gasoline" = "Gasoline")) +
  labs(
    x = "Year",
    y = "Price ($)",
    fill = "Fuel Type",
    title = "Price range across different fuel types during the 2008 recession"
  )

weekly_gas_prices |>
  mutate(
    year = factor(year(date))
  ) |>
  filter(
    year %in% seq(2018, 2025, 1)
  ) |>
  ggplot(aes(x = year, y = price, fill = fuel)) +
  geom_boxplot() +
  labs(
    x = "Year",
    y = "Price ($)",
    fill = "Fuel Type",
    title = "Price range across different fuel types during COVID-19"
  )
```

# Do different grades or formulations of gasoline follow similar trends?

```{r}
weekly_gas_prices |>
  filter(fuel == "gasoline") |>
  group_by(year = year(date), grade) |>
  summarise(
    avg_price = mean(price),
    .groups = "drop"
  ) |>
  ggplot(aes(x = year, y = avg_price)) +
  geom_line(aes(group = grade, color = grade), linewidth = 1)

weekly_gas_prices |>
  filter(fuel == "gasoline") |>
  group_by(year = year(date), formulation) |>
  summarise(
    avg_price = mean(price),
    .groups = "drop"
  ) |>
  ggplot(aes(x = year, y = avg_price)) +
  geom_line(aes(group = formulation, color = formulation), linewidth = 1)
```

```{r}
weekly_gas_prices |>
  ggplot(aes(x = date, y = price, color = fuel)) +
  geom_smooth(se = TRUE, alpha = 0.2) +
  labs(title = "Price Volatility Over Time",
       subtitle = "Shaded areas show confidence intervals",
       x = "Date", 
       y = "Price",
       color = "Fuel Type") +
  theme_minimal()
```

```{r}
ggsave(
  filename = "2008-fuel-price.jpg",
  height = 5,
  width = 7,
  units = "in",
  dpi = 300
)
```









